### ISSUE TITLE
configure: error / No package 'liblz4' found

### ISSUE THREAD

**Issue by nanau25** [CanalTP/asgard#6]
Hi, 
I have a compilation Error.

configure: error: Package requirements (protobuf >= 2.4.0 libcurl >= 7.35.0 zlib >= 1.2.8 liblz4 >= 1.7.3) were not met:
No package 'liblz4' found

==> I installed the lib with the dockerfile (liblz4-dev).
but the header lz4frame.h is not found to compîle valhalla  file "valhalla_pack_elevation.cc"

**Comment by TeXitoi** [comment]
First, this project is highly experimental. I'm curious to know why you want to run it!

The docker file at the root is out of date. (This docker file)[https://github.com/CanalTP/asgard/blob/master/docker/asgard-dev/Dockerfile) should work.

I will update the docker file at the root.

**Comment by nanau25** [comment]
Thanks!

**Comment by TeXitoi** [comment]
I will close it when I'd corrected the Dockerfile.
